#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
python3 scripts/therapy_alert_ack_contract_test.py
python3 scripts/clock_snapshot_contract_test.py
python3 scripts/capacity_snapshot_behavior_test.py
python3 scripts/upload_progress_snapshot_contract_test.py
python3 scripts/idf_async_allocation_test.py
python3 scripts/oximetry_forget_tombstone_contract_test.py
python3 scripts/psram_task_lifecycle_contract_test.py
python3 scripts/backend_runtime_test.py
python3 scripts/session_storage_behavior_test.py
python3 scripts/session_checkpoint_barrier_test.py
python3 scripts/rapid_session_lifecycle_contract_test.py
python3 scripts/session_writer_start_resilience_contract_test.py
python3 scripts/sd_recording_arbitration_contract_test.py
python3 scripts/oximetry_sd_lease_contract_test.py
python3 scripts/sd_mount_fallback_contract_test.py
python3 scripts/backend_recording_test.py
python3 scripts/therapy_lifecycle_race_contract_test.py
python3 scripts/therapy_gate_behavior_test.py
python3 scripts/storage_export_fault_test.py
python3 scripts/edf_rebuild_behavior_test.py
python3 scripts/pending_export_behavior_test.py
python3 scripts/pending_export_service_test.py
python3 scripts/upload_invalidation_behavior_test.py
python3 scripts/backend_realtime_test.py
python3 scripts/uploader_ox_lease_contract_test.py
python3 scripts/fork_backend_reconciliation_test.py

./scripts/test-platform4.sh

./scripts/test-platform5.sh
python3 scripts/qemu_variant_test.py

python3 scripts/font_asset_contract_test.py
python3 scripts/live_flow_units_contract_test.py
python3 scripts/storage_status_memory_contract_test.py
python3 scripts/screen_timeout_contract_test.py
